"use client";

import Link from "next/link";
import { useParams } from "next/navigation";
import { useEffect, useState } from "react";
import type { WorkspaceMemory } from "@mai-chat/shared-types";
import { ApiError, createWorkspaceMemory, deleteWorkspaceMemory, listWorkspaceMemory, updateWorkspaceMemory, type WorkspaceMemoryInput } from "../../../../lib/api";

const blank: WorkspaceMemoryInput = { kind: "knowledge", title: "", content: "", sourceTitle: "", sourceUrl: "", freshUntil: "" };
function dateInput(value: string | null) { return value ? value.slice(0, 10) : ""; }
function stale(memory: WorkspaceMemory) { return Boolean(memory.freshUntil && new Date(memory.freshUntil).getTime() < Date.now()); }
function formatDate(value: string | null) { return value ? new Date(value).toLocaleDateString([], { month: "short", day: "numeric", year: "numeric" }) : "No review date"; }

export default function MemoryPage() {
  const { id: workspaceId } = useParams<{ id: string }>();
  const [memories, setMemories] = useState<WorkspaceMemory[]>([]);
  const [selected, setSelected] = useState<WorkspaceMemory | null>(null);
  const [draft, setDraft] = useState<WorkspaceMemoryInput>(blank);
  const [filter, setFilter] = useState<"all" | "knowledge" | "decision">("all");
  const [error, setError] = useState(""); const [notice, setNotice] = useState(""); const [saving, setSaving] = useState(false);
  const refresh = async () => setMemories(await listWorkspaceMemory(workspaceId));
  useEffect(() => { void refresh().catch((err: Error) => setError(err.message)); }, [workspaceId]);
  function edit(memory: WorkspaceMemory) { setSelected(memory); setDraft({ kind: memory.kind, title: memory.title, content: memory.content, sourceTitle: memory.sourceTitle ?? "", sourceUrl: memory.sourceUrl ?? "", freshUntil: dateInput(memory.freshUntil) }); setError(""); setNotice(""); }
  async function save() { setSaving(true); setError(""); setNotice(""); try { const memory = selected ? await updateWorkspaceMemory(workspaceId, selected.id, draft) : await createWorkspaceMemory(workspaceId, draft); await refresh(); edit(memory); setNotice(selected ? "Memory updated." : "Memory saved for the workspace."); } catch (err) { setError(err instanceof ApiError ? err.message : "Could not save memory."); } finally { setSaving(false); } }
  async function remove() { if (!selected || !window.confirm(`Delete ${selected.title}? This removes it from future agent context.`)) return; setSaving(true); try { await deleteWorkspaceMemory(workspaceId, selected.id); setSelected(null); setDraft(blank); await refresh(); } catch (err) { setError(err instanceof Error ? err.message : "Could not delete memory."); } finally { setSaving(false); } }
  const visible = memories.filter((memory) => filter === "all" || memory.kind === filter);
  return <main className="workspace-settings-page memory-page"><Link href={`/w/${workspaceId}`} className="settings-back">← Back to workspace</Link><header><p className="eyebrow">WORKSPACE MEMORY</p><h1>Keep the context that matters</h1><p>Save shared knowledge and decisions with citations and review dates. Current entries are available to every workspace agent.</p></header><div className="memory-layout">
    <section className="memory-list"><div className="section-heading"><h2>Memory</h2><button onClick={() => { setSelected(null); setDraft(blank); setError(""); setNotice(""); }}>New entry</button></div><div className="memory-filter"><button className={filter === "all" ? "active" : ""} onClick={() => setFilter("all")}>All</button><button className={filter === "knowledge" ? "active" : ""} onClick={() => setFilter("knowledge")}>Knowledge</button><button className={filter === "decision" ? "active" : ""} onClick={() => setFilter("decision")}>Decisions</button></div>{visible.length ? visible.map((memory) => <button key={memory.id} className={`memory-card ${selected?.id === memory.id ? "selected" : ""}`} onClick={() => edit(memory)}><span className={`memory-kind ${memory.kind}`}>{memory.kind}</span><strong>{memory.title}</strong><small>{stale(memory) ? "Needs review" : formatDate(memory.freshUntil)}</small></button>) : <p className="muted">No saved {filter === "all" ? "memory" : filter} yet.</p>}</section>
    <section className="memory-form"><div className="section-heading"><h2>{selected ? selected.title : "New memory"}</h2>{selected && <span className={`memory-review ${stale(selected) ? "stale" : "current"}`}>{stale(selected) ? "Needs review" : selected.freshUntil ? "Current" : "No review date"}</span>}</div><label>Type<select value={draft.kind} onChange={(e) => setDraft({ ...draft, kind: e.target.value as WorkspaceMemoryInput["kind"] })}><option value="knowledge">Knowledge</option><option value="decision">Saved decision</option></select></label><label>Title<input value={draft.title} onChange={(e) => setDraft({ ...draft, title: e.target.value })} placeholder={draft.kind === "decision" ? "Use release branch main" : "Production deployment process"}/></label><label>{draft.kind === "decision" ? "Decision and rationale" : "What the team should know"}<textarea rows={6} value={draft.content} onChange={(e) => setDraft({ ...draft, content: e.target.value })} placeholder="Write the durable context an agent and teammate can rely on."/></label><div className="memory-two-columns"><label>Source title<input value={draft.sourceTitle ?? ""} onChange={(e) => setDraft({ ...draft, sourceTitle: e.target.value })} placeholder="Release plan"/></label><label>Source URL<input type="url" value={draft.sourceUrl ?? ""} onChange={(e) => setDraft({ ...draft, sourceUrl: e.target.value })} placeholder="https://..."/></label></div><label>Review by <input type="date" value={draft.freshUntil ?? ""} onChange={(e) => setDraft({ ...draft, freshUntil: e.target.value || null })}/><small className="field-help">Entries past this date remain visible but agents are instructed to verify them.</small></label>{selected && <p className="memory-meta">Saved by {selected.createdByName ?? "a former member"} · updated {new Date(selected.updatedAt).toLocaleString()}</p>}{error && <p className="error-text">{error}</p>}{notice && <p className="success-text">{notice}</p>}<div className="agent-builder-actions"><button className="primary-button" disabled={saving || !draft.title.trim() || !draft.content.trim()} onClick={() => void save()}>{saving ? "Saving…" : selected ? "Save changes" : "Save memory"}</button>{selected && <button className="agent-delete-button" disabled={saving} onClick={() => void remove()}>Delete memory</button>}</div>{selected?.sourceUrl && <a className="memory-source-link" href={selected.sourceUrl} target="_blank" rel="noreferrer">Open cited source ↗</a>}</section>
  </div></main>;
}
