"use client";

import { useEffect, useState } from "react";
import Link from "next/link";
import { useParams } from "next/navigation";
import type { WorkspaceNotification, WorkspaceNotificationPreferences } from "@mai-chat/shared-types";
import { getNotificationPreferences, listNotifications, markNotificationsRead, updateNotificationPreferences } from "../../../../lib/api";

const empty: WorkspaceNotificationPreferences = { workspaceId: "", browserEnabled: true, emailEnabled: false, slackEnabled: false, escalationMinutes: 60, dailySummaryEnabled: true, updatedAt: null };
function relativeTime(value: string) { const mins = Math.max(0, Math.floor((Date.now() - new Date(value).getTime()) / 60000)); return mins < 1 ? "Just now" : mins < 60 ? `${mins}m ago` : mins < 1440 ? `${Math.floor(mins / 60)}h ago` : `${Math.floor(mins / 1440)}d ago`; }

export default function NotificationsPage() {
  const { id: workspaceId } = useParams<{ id: string }>();
  const [items, setItems] = useState<WorkspaceNotification[]>([]);
  const [preferences, setPreferences] = useState<WorkspaceNotificationPreferences>(empty);
  const [saving, setSaving] = useState(false);
  const [notice, setNotice] = useState("");
  useEffect(() => { Promise.all([listNotifications(workspaceId), getNotificationPreferences(workspaceId)]).then(([notifications, settings]) => { setItems(notifications); setPreferences(settings); }).catch(() => setNotice("Could not load notification settings.")); }, [workspaceId]);
  async function save(next: Partial<WorkspaceNotificationPreferences>) { setSaving(true); setNotice(""); try { const updated = await updateNotificationPreferences(workspaceId, next); setPreferences(updated); setNotice("Settings saved."); } catch { setNotice("Could not save notification settings."); } finally { setSaving(false); } }
  async function markAllRead() { await markNotificationsRead(workspaceId); setItems((current) => current.map((item) => ({ ...item, readAt: item.readAt ?? new Date().toISOString() }))); }
  const unread = items.filter((item) => !item.readAt).length;
  return <main className="notifications-page"><header className="notifications-header"><div><p className="eyebrow">PERSONAL NOTIFICATIONS</p><h1>Stay informed on your terms</h1><span>Choose which workspace updates reach you, where they arrive, and when they should escalate.</span></div><Link href={`/w/${workspaceId}`} className="secondary-button">Back to chat</Link></header>
    <div className="notifications-grid"><section className="notification-card notification-inbox"><header><div><p>Inbox</p><h2>{unread ? `${unread} unread update${unread === 1 ? "" : "s"}` : "You’re all caught up"}</h2></div>{items.length > 0 && <button className="text-button" onClick={() => void markAllRead()}>Mark all read</button>}</header>{items.length ? <div>{items.map((item) => <article className={item.readAt ? "read" : "unread"} key={item.id}><span className={`notification-kind ${item.kind}`} /><div><strong>{item.kind.replaceAll("_", " ")}</strong><p>{item.text}</p></div><time>{relativeTime(item.createdAt)}</time></article>)}</div> : <div className="notification-empty">Agent completions, decisions, and governed action updates will appear here.</div>}</section>
      <section className="notification-card notification-settings"><header><div><p>Delivery routing</p><h2>Choose your channels</h2></div></header><div className="notification-options"><label><span><strong>Browser notifications</strong><small>Show workspace updates in the product notification center.</small></span><input type="checkbox" checked={preferences.browserEnabled} disabled={saving} onChange={(event) => void save({ browserEnabled: event.target.checked })}/></label><label><span><strong>Email routing</strong><small>Save email delivery preference for completion and decision alerts.</small></span><input type="checkbox" checked={preferences.emailEnabled} disabled={saving} onChange={(event) => void save({ emailEnabled: event.target.checked })}/></label><label><span><strong>Slack routing</strong><small>Save Slack delivery preference for connected workspace channels.</small></span><input type="checkbox" checked={preferences.slackEnabled} disabled={saving} onChange={(event) => void save({ slackEnabled: event.target.checked })}/></label></div><p className="notification-channel-note">Email and Slack preferences are ready for routing when those outbound delivery channels are enabled for this workspace.</p></section>
      <section className="notification-card notification-escalation"><header><div><p>Escalation</p><h2>Follow up when a decision waits</h2></div></header><label className="notification-select"><span>Escalate an unread decision after</span><select value={preferences.escalationMinutes} disabled={saving} onChange={(event) => void save({ escalationMinutes: Number(event.target.value) })}><option value={15}>15 minutes</option><option value={30}>30 minutes</option><option value={60}>1 hour</option><option value={240}>4 hours</option><option value={1440}>1 day</option></select></label><p>Escalations apply to decision requests that remain unread in your workspace inbox.</p></section>
      <section className="notification-card notification-digest"><header><div><p>Daily summary</p><h2>A concise workspace digest</h2></div></header><label className="digest-toggle"><span><strong>Send a daily activity summary</strong><small>Receive one digest of completed work, decisions, and workflow failures.</small></span><input type="checkbox" checked={preferences.dailySummaryEnabled} disabled={saving} onChange={(event) => void save({ dailySummaryEnabled: event.target.checked })}/></label><p>Daily summaries follow your chosen delivery routing.</p></section></div>{notice && <p className="notification-notice">{notice}</p>}
  </main>;
}
