"use client";

import { useEffect, useMemo, useState } from "react";
import Link from "next/link";
import { useParams } from "next/navigation";
import type { WorkspaceNotification, WorkspaceNotificationPreferences } from "@mai-chat/shared-types";
import { cancelAction, confirmAction, getNotificationPreferences, listNotifications, markNotificationSelectionRead, markNotificationsRead, updateNotificationPreferences } from "../../../../lib/api";

const empty: WorkspaceNotificationPreferences = { workspaceId: "", browserEnabled: true, escalationMinutes: 60, dailySummaryEnabled: true, quietHoursEnabled: false, quietHoursStart: 20, quietHoursEnd: 8, digestHour: 9, updatedAt: null };
type Filter = "all" | "unread" | "approvals" | "workflows" | "system";
function relativeTime(value: string) { const mins = Math.max(0, Math.floor((Date.now() - new Date(value).getTime()) / 60000)); return mins < 1 ? "Just now" : mins < 60 ? `${mins}m ago` : mins < 1440 ? `${Math.floor(mins / 60)}h ago` : `${Math.floor(mins / 1440)}d ago`; }
function destination(item: WorkspaceNotification, workspaceId: string) { if (item.resourceType === "workflow") return `/w/${workspaceId}/observability`; if (item.resourceType === "artifact") return `/w/${workspaceId}/artifacts`; if (item.resourceType === "integration") return `/w/${workspaceId}/integrations`; return item.conversationId ? `/w/${workspaceId}?conversationId=${item.conversationId}` : `/w/${workspaceId}/activity`; }

export default function NotificationsPage() {
  const { id: workspaceId } = useParams<{ id: string }>();
  const [items, setItems] = useState<WorkspaceNotification[]>([]); const [preferences, setPreferences] = useState(empty); const [filter, setFilter] = useState<Filter>("all"); const [query, setQuery] = useState(""); const [selected, setSelected] = useState<string[]>([]); const [saving, setSaving] = useState(false); const [notice, setNotice] = useState("");
  useEffect(() => { Promise.all([listNotifications(workspaceId), getNotificationPreferences(workspaceId)]).then(([notifications, settings]) => { setItems(notifications); setPreferences(settings); }).catch(() => setNotice("Could not load notification settings.")); }, [workspaceId]);
  async function save(next: Partial<WorkspaceNotificationPreferences>) { setSaving(true); setNotice(""); try { const updated = await updateNotificationPreferences(workspaceId, next); setPreferences(updated); setNotice("Settings saved."); } catch { setNotice("Could not save notification settings."); } finally { setSaving(false); } }
  async function markRead(ids?: string[]) { if (ids?.length) await markNotificationSelectionRead(workspaceId, ids); else await markNotificationsRead(workspaceId); const set = new Set(ids ?? items.map((item) => item.id)); setItems((current) => current.map((item) => set.has(item.id) ? { ...item, readAt: item.readAt ?? new Date().toISOString() } : item)); setSelected([]); }
  async function resolveAction(item: WorkspaceNotification, intent: "confirm" | "cancel") { if (!item.resourceId) return; setSaving(true); try { if (intent === "confirm") await confirmAction(workspaceId, item.resourceId, "Workspace member"); else await cancelAction(workspaceId, item.resourceId, "Workspace member"); await markRead([item.id]); setNotice(intent === "confirm" ? "Action approved." : "Action declined."); } catch (reason) { setNotice(reason instanceof Error ? reason.message : "Could not resolve action."); } finally { setSaving(false); } }
  const filtered = useMemo(() => items.filter((item) => { const searchable = `${item.kind} ${item.text}`.toLowerCase().includes(query.toLowerCase()); const matches = filter === "all" || filter === "unread" && !item.readAt || filter === "approvals" && ["decision_needed", "permission_request", "action_completed"].includes(item.kind) || filter === "workflows" && item.kind === "workflow_alert" || filter === "system" && item.kind === "agent_completed"; return searchable && matches; }), [filter, items, query]);
  const groups = useMemo(() => Object.values(filtered.reduce<Record<string, WorkspaceNotification[]>>((all, item) => { const key = item.groupKey ?? item.id; (all[key] ??= []).push(item); return all; }, {})), [filtered]);
  const unread = items.filter((item) => !item.readAt).length;
  return <main className="notifications-page"><header className="notifications-header"><div><p className="eyebrow">PERSONAL NOTIFICATIONS</p><h1>Notification center</h1><span>Review actionable workspace updates and control your in-app inbox.</span></div><Link href={`/w/${workspaceId}`} className="secondary-button">Back to chat</Link></header>
    <section className="notification-summary"><article><span>Unread</span><strong>{unread}</strong></article><article><span>High priority</span><strong>{items.filter((item) => item.priority === "high" && !item.readAt).length}</strong></article><article><span>Active rules</span><strong>{preferences.dailySummaryEnabled ? 2 : 1}</strong></article><article><span>Delivery health</span><strong>In-app</strong><small>Notifications follow your saved in-app preference.</small></article></section>
    <div className="notifications-grid"><section className="notification-card notification-inbox"><header><div><p>Inbox</p><h2>{unread ? `${unread} unread update${unread === 1 ? "" : "s"}` : "You’re all caught up"}</h2></div><button className="text-button" onClick={() => void markRead()}>Mark all read</button></header><div className="notification-toolbar"><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search notification history" aria-label="Search notifications" /><div>{(["all", "unread", "approvals", "workflows", "system"] as Filter[]).map((value) => <button key={value} className={filter === value ? "active" : ""} onClick={() => setFilter(value)}>{value}</button>)}</div>{selected.length > 0 && <button onClick={() => void markRead(selected)}>Mark {selected.length} read</button>}</div>{groups.length ? <div>{groups.map((group) => { const item = group[0]; return <article className={`notification-row ${item.readAt ? "read" : "unread"} priority-${item.priority}`} key={item.groupKey ?? item.id}><input type="checkbox" checked={selected.includes(item.id)} onChange={(event) => setSelected((current) => event.target.checked ? [...current, item.id] : current.filter((id) => id !== item.id))} /><span className={`notification-kind ${item.kind}`} /><div><strong>{item.kind.replaceAll("_", " ")}{group.length > 1 ? ` · ${group.length} updates` : ""}</strong><p>{item.text}</p><small>{item.priority} priority · {relativeTime(item.createdAt)}</small></div>{item.resourceType === "action" && !item.readAt ? <div className="notification-actions"><button disabled={saving} onClick={() => void resolveAction(item, "confirm")}>Approve</button><button disabled={saving} onClick={() => void resolveAction(item, "cancel")}>Decline</button></div> : <Link href={destination(item, workspaceId)}>Open</Link>}</article>; })}</div> : <div className="notification-empty">No notifications match these filters.</div>}</section>
      <section className="notification-card notification-settings"><header><div><p>In-app delivery</p><h2>Control your inbox</h2></div></header><div className="notification-options"><label><span><strong>In-app notifications</strong><small>Show alerts, approvals, and workflow updates in this notification center.</small></span><input type="checkbox" checked={preferences.browserEnabled} disabled={saving} onChange={(event) => void save({ browserEnabled: event.target.checked })}/></label></div></section>
      <section className="notification-card notification-escalation"><header><div><p>Escalation and quiet hours</p><h2>Control interruption</h2></div></header><label className="notification-select"><span>Escalate unread approvals after</span><select value={preferences.escalationMinutes} disabled={saving} onChange={(event) => void save({ escalationMinutes: Number(event.target.value) })}><option value={15}>15 minutes</option><option value={30}>30 minutes</option><option value={60}>1 hour</option><option value={240}>4 hours</option><option value={1440}>1 day</option></select></label><label className="digest-toggle"><span><strong>Quiet hours</strong><small>Suppress non-critical delivery between selected hours.</small></span><input type="checkbox" checked={preferences.quietHoursEnabled} onChange={(event) => void save({ quietHoursEnabled: event.target.checked })}/></label>{preferences.quietHoursEnabled && <div className="notification-time-range"><select value={preferences.quietHoursStart} onChange={(event) => void save({ quietHoursStart: Number(event.target.value) })}>{Array.from({ length: 24 }, (_, hour) => <option key={hour} value={hour}>{hour}:00</option>)}</select><span>to</span><select value={preferences.quietHoursEnd} onChange={(event) => void save({ quietHoursEnd: Number(event.target.value) })}>{Array.from({ length: 24 }, (_, hour) => <option key={hour} value={hour}>{hour}:00</option>)}</select></div>}</section>
      <section className="notification-card notification-digest"><header><div><p>Digest schedule</p><h2>A concise workspace summary</h2></div></header><label className="digest-toggle"><span><strong>Send a daily activity digest</strong><small>Completed work, decisions, workflow failures, and unresolved approvals.</small></span><input type="checkbox" checked={preferences.dailySummaryEnabled} disabled={saving} onChange={(event) => void save({ dailySummaryEnabled: event.target.checked })}/></label><label className="notification-select"><span>Digest time</span><select value={preferences.digestHour} disabled={saving || !preferences.dailySummaryEnabled} onChange={(event) => void save({ digestHour: Number(event.target.value) })}>{Array.from({ length: 24 }, (_, hour) => <option key={hour} value={hour}>{hour}:00</option>)}</select></label></section></div>{notice && <p className="notification-notice">{notice}</p>}
  </main>;
}
