"use client";
export type ReportVisualLayout = "operating" | "timeline" | "impact" | "decisions" | "health" | "digest";
export const reportVisualLayouts: Array<{id: ReportVisualLayout; label: string; detail: string}> = [
  {id:"operating",label:"Operating review",detail:"Leadership health and actions"},{id:"timeline",label:"Progress timeline",detail:"What changed and what is next"},{id:"impact",label:"Impact report",detail:"Before, after, and evidence"},{id:"decisions",label:"Decision briefing",detail:"Choices requiring ownership"},{id:"health",label:"Project health",detail:"Readiness, risk, and milestones"},{id:"digest",label:"Team update digest",detail:"A concise stakeholder update"},
];
type Group={title:string;items:string[]};
function clean(v:string){return v.replace(/^#{1,6}\s+|^[-*+]\s+|\*\*/g,"").replace(/[|]/g,"·").replace(/\s+/g," ").trim()}
function parse(content:string){const parts=content.split(/^##\s+/m).filter(Boolean);const groups:Group[]=parts.map(p=>{const [title,...rest]=p.split("\n");return{title:clean(title)||"Update",items:rest.map(clean).filter(x=>x&&!/^[-· :]+$/.test(x))}});const all=groups.flatMap(g=>g.items);return{groups:groups.length?groups:[{title:"Update",items:all}],all}}
export function ReportVisual({title,summary,content,layout}:{title:string;summary:string;content:string;layout:ReportVisualLayout}){const data=parse(content);const first=data.all.slice(0,6);const risks=data.groups.find(g=>/risk|block/i.test(g.title))?.items??[];const decisions=data.groups.find(g=>/decision|ask/i.test(g.title))?.items??[];const next=data.groups.find(g=>/next|action/i.test(g.title))?.items[0]??first[0]??"Add a next step.";return <section className={`report-visual report-${layout}`}><header><p>TEAM REPORT</p><h2>{title||"Untitled report"}</h2><span>{summary||"A concise update for the team."}</span></header>
{layout==="operating"&&<div className="report-operating"><article className="operating-health"><span>OVERALL HEALTH</span><b>{risks.length?"At risk":"On track"}</b><small>{risks.length?`${risks.length} item${risks.length===1?"":"s"} needs attention`:"No active blockers"}</small></article><article><span>KEY CHANGE</span><p>{first[0]||"Add report context."}</p></article><article><span>DECISION</span><p>{decisions[0]||"No decision needed."}</p></article><article><span>NEXT ACTION</span><p>{next}</p></article></div>}
{layout==="timeline"&&<div className="report-timeline">{first.map((item,i)=><article key={item}><i/><span>{i===0?"Completed":i===first.length-1?"Next":"In progress"}</span><p>{item}</p></article>)}</div>}
{layout==="impact"&&<div className="report-impact"><article><span>BEFORE</span><p>{first[0]||"Baseline not recorded."}</p></article><i>→</i><article><span>NOW</span><p>{first[1]||"Current outcome not recorded."}</p></article><article className="impact-evidence"><span>EVIDENCE & IMPACT</span><p>{first.slice(2,4).join(" · ")||"Add evidence from the team."}</p></article></div>}
{layout==="decisions"&&<div className="report-decision-list">{(decisions.length?decisions:first.slice(0,4)).map((item,i)=><article key={item}><b>D{i+1}</b><div><span>DECISION REQUIRED</span><p>{item}</p></div><small>{i===0?"Owner needed":"Review this week"}</small></article>)}</div>}
{layout==="health"&&<div className="report-health"><article className="health-ring"><b>{risks.length?68:86}</b><small>health</small></article><article><span>RISKS</span><strong>{risks.length}</strong><small>{risks[0]||"None recorded"}</small></article><article><span>PROGRESS</span><strong>{Math.min(100,55+first.length*7)}%</strong><small>{first[0]||"Add progress update"}</small></article><article><span>UP NEXT</span><p>{next}</p></article></div>}
{layout==="digest"&&<div className="report-digest"><article><span>FOR STAKEHOLDERS</span><h3>{summary||"Team update"}</h3><p>{first[0]||"Add the primary update."}</p></article><section><h4>Accomplished</h4><ul>{first.slice(0,3).map(x=><li key={x}>{x}</li>)}</ul><h4>Next</h4><p>{next}</p></section></div>}
</section>}
