// Health checks and public share-link views (no sign-in).
import * as db from "@mai-chat/db";
import { errMessage, paramString } from "../http-utils.js";
import type { Request, Response } from "express";
import type { RouteContext } from "./context.js";

export function registerPublicRoutes({ app }: RouteContext): void {
  // Liveness proves the process can answer HTTP; readiness also proves its
  // required datastore is reachable. Neither endpoint leaks configuration.
  app.get("/healthz", (_req: Request, res: Response) => res.json({ ok: true, service: "chat-server" }));

  // Unauthenticated on purpose -- this is the public read-only link
  // generated by POST .../share below. Returns only the safe subset
  // (see PublicDashboardView); never the full artifact, and only while
  // the dashboard is published and a share link is still active.
  app.get("/public/dashboards/:token", async (req: Request, res: Response) => {
    const token = paramString(req.params.token);
    if (!token) return res.status(404).json({ error: "not found" });
    const view = await db.getPublicDashboardByShareToken(token);
    if (!view) return res.status(404).json({ error: "This dashboard link is no longer available." });
    res.json(view);
  });

  app.get("/public/release-notes/:token", async (req: Request, res: Response) => {
    const token = paramString(req.params.token);
    if (!token) return res.status(404).json({ error: "not found" });
    const view = await db.getPublicReleaseNotesByShareToken(token);
    if (!view) return res.status(404).json({ error: "This release notes link is no longer available." });
    res.json(view);
  });

  // Same pattern as the two routes above, for the three artifact types
  // (Plan, Report, Task list) that share one generic public view instead
  // of a type-specific one -- see PublicArtifactView and
  // getPublicArtifactByShareToken's own type filter.
  app.get("/public/artifacts/:token", async (req: Request, res: Response) => {
    const token = paramString(req.params.token);
    if (!token) return res.status(404).json({ error: "not found" });
    const view = await db.getPublicArtifactByShareToken(token);
    if (!view) return res.status(404).json({ error: "This artifact link is no longer available." });
    res.json(view);
  });
  app.get("/readyz", async (_req: Request, res: Response) => {
    try {
      await db.checkDatabaseHealth();
      res.json({ ok: true, service: "chat-server", database: "connected" });
    } catch (error) {
      console.error(JSON.stringify({ level: "error", event: "readiness_check_failed", error: errMessage(error) }));
      res.status(503).json({ ok: false, service: "chat-server", database: "unavailable" });
    }
  });
}
